<div class="header"> 
	<h1 class="page-title">用户列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<?php if(@$_GET['date']){?>
	<li><a href="/statistics/nuser">用户统计</a> <span class="divider">/</span></li>
	<?php }?>
	<li class="active">用户列表</li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<table class="table table-bordered table-hover">
		<caption></caption>
		  <thead>
		    <tr>
		      <th>姓名</th>
		      <th>手机</th>
		      <th>邮箱</th>	      		      
		      <th>职业</th>
		      <th>性别</th>
		      <th>积分</th>
		      <th>详情</th>
		      <th>修改</th>
		      <th>删除</th>   
		    </tr>
		  </thead>
		  <tbody>
		  <?php if(count($this->res)>0){?>
		  <?php foreach ($this->res as $record){?>
		  <tr>
			  <td><?php echo $record['name'];?></td>
			  <td><?php echo $record['mobile'];?></td>
			  <td><?php echo $record['email'];?></td>
			  <td><?php echo $record['job'];?></td>
			  <td><?php if($record['sex']==1){echo "男";}elseif($record['sex']==2){echo "女";}else{echo "未设置";}?></td>
			  <td><?php echo $record['point'];?></td>
			  <td><a href="/nuser/view?id=<?php echo $record['id'];?>">详情</a></td>
			  <td><a href="/nuser/update?id=<?php echo $record['id'];?>">修改</a></td>
			  <td><a href="#myModal<?php echo $record['id'];?>" role="button"  data-toggle="modal" >删除</a></td>
		  </tr>
<!-- Modal -->
<div id="myModal<?php echo $record['id'];?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">删除账号为（<?php if($record['mobile']){echo $record['mobile'];}else{echo $record['email'];}?>）的用户</h3>
  </div>
  <div class="modal-body">
    <p>您确定删除账号为（<?php if($record['mobile']){echo $record['mobile'];}else{echo $record['email'];} ?>）的用户吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $record['id'];?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $record['id'];?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/nuser/delete",
				data:"id=<?php echo $record['id'];?>",
				success:
					location.reload(),
			});
		});
});

</script>		  
		  <?php }?>
		  <?php }else{?>
		  <tr>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>		  
		  </tr>	
		  <?php }?>	  
		  
		  </tbody>
		  </table>
		  
		  <div class="pagination" style="text-align: center;">
		  <ul>
		  <?php if($this->res->getCurrentPageNumber()<=1){ ?>
		  <li><a href="/nuser/detail?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber();?>" class="disabled btn"> 前一页 </a></li>
		  <?php }else{?>
		  <li><a href="/nuser/detail?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber() - 1;?>"> 前一页 </a></li>
		  <?php }?>
		    
		  <?php if($this->res->getCurrentPageNumber()>=$this->res->count()){ ?> 
		  <li><a href="/nuser/detail?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber();?>" class="disabled btn"> 后一页</a></li>
		  <?php }else{ ?> 
		  <li><a href="/nuser/detail?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber() + 1;?>"> 后一页</a></li>		  
		  <?php }?>
		  </ul>
		</div>
		  
		  
		  
		  
		  
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>