<div class="header"> 
	<h1 class="page-title">查找用户</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">查找用户</li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
			<label>根据邮箱查找</label>
			<form class="form-search">
			  <input type="text" class="input-medium search-query" name="email">
			  <button type="submit" class="btn">搜索</button>
			</form>
			
			<label>根据手机号码查找</label>
			<form class="form-search">
			  <input type="text" class="input-medium search-query" name="mobile">
			  <button type="submit" class="btn">搜索</button>
			</form>

			

	  

		  <?php if(count($this->nusers)>0){?>
		  	<table class="table table-bordered table-hover">
			<caption></caption>
			<thead>
		    <tr>
		      <th>姓名</th>
		      <th>手机</th>
		      <th>邮箱</th>	      		      
		      <th>职业</th>
		      <th>性别</th>
		      <th>积分</th>
		      <th>详情</th>   
		      <th>修改</th>  
		      <th>删除</th>
		    </tr>
		  </thead>
		  <tbody>
		  <?php foreach ($this->nusers as $record){?>
		  <tr>
			  <td><?php echo $record->getName();?></td>
			  <td><?php echo $record->getMobile();?></td>
			  <td><?php echo $record->getEmail();?></td>
			  <td><?php echo $record->getJob();?></td>
			  <td><?php if($record->getSex()==1){echo "男";}elseif($record->getSex()==2){echo "女";}else{echo "暂未设置";}?></td>
			  <td><?php echo $record->getPoint();?></td>
			  <td><a href="/nuser/view?id=<?php echo $record->getId();?>">详情</a></td>
			  <td><a href="/nuser/update?id=<?php echo $record->getId();?>">修改</a></td>
			   <td><a href="#myModal<?php echo $record->getId();?>" role="button"  data-toggle="modal" >删除</a></td>
		  </tr>
<!-- Modal -->
<div id="myModal<?php echo $record->getId();?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">删除账号为（<?php if(@$_GET['mobile']){echo $record->getMobile();}else{echo $record->getEmail();}?>）的用户</h3>
  </div>
  <div class="modal-body">
    <p>您确定删除账号为（<?php if(@$_GET['mobile']){echo $record->getMobile();}else{echo $record->getEmail();} ?>）的用户吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $record->getId();?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $record->getId();?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/nuser/delete",
				data:"id=<?php echo $record->getId();?>",
				success:
					location.reload(),
			});
		});
});

</script>		  
		  <?php }?>
		  </tbody>
		  </table>
		  <?php } ?>
			
			
			
			
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>