<?php $nuser = $this->nuser;?>
<div class="header">
	<h1 class="page-title">修改用户信息</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/nuser/detail">用户列表</a> <span class="divider">/</span></li>
	<li class="active">修改用户信息</li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->

<br />
<form class="form-horizontal" action="/nuser/updateajax" method="post" enctype="multipart/form-data">

 <input type="hidden" id="inputId" placeholder="<?php echo $nuser->getId();?>" class="span8" name="id" value="<?php echo $nuser->getId();?>">

  <div class="control-group">
    <label class="control-label" for="inputName">姓名</label>
    <div class="controls">
      <input type="text" id="inputName" placeholder="<?php echo $nuser->getName();?>" class="span8" name="name">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputFile">头像</label>
    <div class="controls">
      <input type="file" id="inputFile" class="span8" name="avatar">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputSex">性别</label>
    <div class="controls">
     <select id="inputSex" name="sex" class="span8">
     <?php $sex = $nuser->getSex();
     if($sex == 1){
	 ?>	
	  <option value ="1" selected="selected">男</option>
	  <option value ="2">女</option>
	  <option value ="3">未设置</option>
     <?php }elseif($sex==2){?>
	  <option value ="1">男</option>
	  <option value ="2" selected="selected">女</option>
	  <option value ="3">未设置</option>
	<?php }else{?>
	 <option value ="1">男</option>
	  <option value ="2">女</option>
	  <option value ="3" selected="selected">未设置</option>
	<?php }?>
	</select>
    </div>
  </div>
   
  
  <div class="control-group">
    <label class="control-label" for="inputMobile">手机</label>
    <div class="controls">
      <input type="text" id="inputMobile" placeholder="<?php echo $nuser->getMobile();?>" class="span8" name="mobile">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputEmail">邮箱</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="<?php echo $nuser->getEmail();?>" class="span8" name="email">
    </div>
  	</div>
  	
  	
  <div class="control-group">
    <label class="control-label" for="inputPhone">电话</label>
    <div class="controls">
      <input type="text" id="inputPhone" placeholder="<?php echo $nuser->getPhone();?>" class="span8" name="phone">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputPasswd">密码</label>
    <div class="controls">
      <input type="password" id="inputPasswd" placeholder="输入该值进行改密码操作" class="span8" name="passwd" >
    </div>
  </div>
  
  

  <div class="control-group">
    <label class="control-label" for="inputJob">职业</label>
    <div class="controls">
      <input type="text" id="inputJob" placeholder="<?php echo $nuser->getJob();?>" class="span8" name="job">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputPostcode">邮编</label>
    <div class="controls">
      <input type="text" id="inputPostcode" placeholder="<?php echo $nuser->getPostcode();?>" class="span8" name="postcode">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputIdcard">证件号码</label>
    <div class="controls">
      <input type="text" id="inputIdcard" placeholder="<?php echo $nuser->getIdcard();?>" class="span8" name="idcard">
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputPoint">积分</label>
    <div class="controls">
      <input type="text" id="inputPoint" placeholder="<?php echo $nuser->getPoint();?>" class="span8" name="point">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputCountry">国家</label>
    <div class="controls">
      <input type="text" id="inputCountry" placeholder="<?php echo $nuser->getCountry();?>" class="span8" name="country">
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputAddress">住址</label>
    <div class="controls">
      <input type="text" id="inputAddress" placeholder="<?php echo $nuser->getAddress();?>" class="span8" name="address">
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputBirthday">生日</label>
    <div class="controls">
      <input type="text" id="inputBirthday" placeholder="<?php echo $nuser->getBirthday();?>" class="span8" name="birthday">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputStatus">状态</label>
    <div class="controls">
     <select id="inputStatus" name="status" class="span8">
     <?php $status = $nuser->getStatus();
     if($status == 1){
     ?>
	  <option value ="1" selected="selected">正常</option>
	  <option value ="0">禁用</option>
	  <?php }else{?>
	  <option value ="1">正常</option>
	  <option value ="0" selected="selected">禁用</option>
	  <?php }?>
	</select>
    </div>
  </div>
  
  
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">保存</button>
      <button type="reset" class="btn">重置</button>
    </div>
  </div>
</form>




		<footer>
			<hr>
			<p class="pull-right">虹桥医游网移动互联网项目</p>
			<p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com"
					target="_blank">虹桥医游网</a>
			</p>
		</footer>

	</div>
</div>