<div class="header"> 
	<h1 class="page-title">新增医生</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">新增医生</li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<br />
		<form class="form-horizontal" action="/doctor/updateajax" method="post" enctype="multipart/form-data">

  
  <div class="control-group">
    <label class="control-label" for="inputName">姓名</label>
    <div class="controls">
      <input type="text" id="inputName" placeholder="请输入医生姓名" class="span8" name="name">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputFile">头像</label>
    <div class="controls">
      <input type="file" id="inputFile" class="span8" name="avatar">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputSex">性别</label>
    <div class="controls">
     <select id="inputSex" name="sex" class="span8">
	  <option value ="1">男</option>
	  <option value ="2">女</option>
	  <option value ="3">未设置</option>
	</select>
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputBirthday">生日</label>
    <div class="controls">
      <input type="text" id="inputBirthday" placeholder="请输入医生生日" class="span8" name="birthday">
    </div>
  	</div>
  	
  	
  <div class="control-group">
    <label class="control-label" for="inputEmail">邮箱</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="请输入医生邮箱" class="span8" name="email">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputPasswd">密码</label>
    <div class="controls">
      <input type="password" id="inputPasswd" placeholder="请输入医生密码" class="span8" name="passwd" >
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputDepartment">科室</label>
    <div class="controls">
      <input type="text" id="inputDepartment" placeholder="请输入医生科室" class="span8" name="department">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="inputPoint">积分</label>
    <div class="controls">
      <input type="text" id="inputPoint" placeholder="请输入医生积分，默认0" class="span8" name="point">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputCity">城市</label>
    <div class="controls">
      <input type="text" id="inputCity" placeholder="请输入医生城市" class="span8" name="city">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="inputCertified">认证级别</label>
    <div class="controls">
     <select id="inputCertified" name="certified" class="span8">
	  <option value ="1">★</option>
	  <option value ="2">★★</option>
	  <option value ="3">★★★</option>
	  <option value ="4">★★★★</option>
	  <option value ="5">★★★★★</option>
	</select>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputSpecial">擅长</label>
    <div class="controls">
      <input type="text" id="inputSpecial" placeholder="请输入医生擅长领域" class="span8" name="special">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputCountry">国家</label>
    <div class="controls">
      <input type="text" id="inputCountry" placeholder="请输入医生国家>" class="span8" name="country">
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputIntroduction">简介</label>
    <div class="controls">
      <input type="text" id="inputIntroduction" placeholder="请输入医生简介" class="span8" name="introduction">
    </div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label" for="inputHospital">所属医院</label>
    <div class="controls">
      <input type="text" id="inputHospital" placeholder="请输入医生所属医院" class="span8" name="hospital">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputArea">区域</label>
    <div class="controls">
      <input type="text" id="inputArea" placeholder="请输入医生所在区域" class="span8" name="area">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputQualification">资质</label>
    <div class="controls">
      <input type="text" id="inputQualification" placeholder="请输入医生资质" class="span8" name="qualification">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputReservation_fee">预约费用</label>
    <div class="controls">
      <input type="text" id="inputReservation_fee" placeholder="请输入该医生预约费用，默认0，即免费" class="span8" name="reservation_fee">
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="inputReservation_number">预约人数</label>
    <div class="controls">
      <input type="text" id="inputReservation_number" placeholder="请输入该医生预约人数，默认0" class="span8" name="reservation_number">
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputStatus">状态</label>
    <div class="controls">
     <select id="inputStatus" name="status" class="span8">
	  <option value ="1">正常</option>
	  <option value ="0">禁用</option>
	</select>
    </div>
  </div>
  
  
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">保存</button>
      <button type="reset" class="btn">重置</button>
    </div>
  </div>
</form>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>