<?php $doctor = $this->doctor;?>
<div class="header"> 
	<h1 class="page-title">医生详情</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/doctor/detail">医生列表</a> <span class="divider">/</span></li>
	<li class="active">医生详情</li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($doctor){?>
		<table class="table table-bordered table-hover">
<!--
		<tr>
		<td>编号</td>
		<td><?php echo $doctor->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width: 10%;">姓名</td>
		<td><?php echo $doctor->getName();?></td>
		</tr>
		<tr>
		<td>头像</td>
		<td><img src="/doctor/image?id=<?php echo $doctor->getId();?>" height="120" width="120" /></td>
		</tr>
		<tr>
		<td>性别</td>
		<td><?php if($doctor->getSex()==1){echo "男";}elseif($doctor->getSex()==2){echo '女';}else{echo "未设置";}?></td>
		</tr>		
		<tr>
		<td>生日</td>
		<td><?php echo $doctor->getBirthday();?></td>
		</tr>
		<tr>
		<td>邮箱</td>
		<td><?php echo $doctor->getEmail();?></td>
		</tr>
		<tr>
		<td>科室</td>
		<td><?php echo $doctor->getDepartment();?></td>
		</tr>
		<tr>
		<td>积分</td>
		<td><?php echo $doctor->getPoint();?></td>
		</tr>		
		<tr>
		<td>城市</td>
		<td><?php echo $doctor->getCity();?></td>
		</tr>
		<tr>
		<td>认证级别</td>
		<td><?php echo Yy_Utils::getCertifiedStar($doctor->getCertified());?></td>
		</tr>

		<tr>
		<td>擅长</td>
		<td><?php echo $doctor->getSpecial();?></td>
		</tr>
		<tr>
		<td>国家</td>
		<td><?php echo $doctor->getCountry();?></td>
		</tr>
		<tr>
		<td>简介</td>
		<td><?php echo $doctor->getIntroduction();?></td>
		</tr>
		<tr>
		<td>所属医院</td>
		<td><?php echo $doctor->getHospital();?></td>
		</tr>
		<tr>
		<td>区域</td>
		<td><?php echo $doctor->getArea();?></td>
		</tr>
		<tr>
		<td>资质</td>
		<td><?php echo $doctor->getQualification();?></td>
		</tr>
		<tr>
		<td>预约费用</td>
		<td><?php echo $doctor->getReservation_fee();?></td>
		</tr>
		<tr>
		<td>预约人数</td>
		<td><?php echo $doctor->getReservation_number();?></td>
		</tr>
		<tr>
		<td>创建时间</td>
		<td><?php echo $doctor->getCtime();?></td>
		</tr>
		<tr>
		<td>更新时间</td>
		<td><?php echo $doctor->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($doctor->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<div style="width:20%">
		<a href="/doctor/update?id=<?php echo $doctor->getId();?>" class="btn btn-block">是否修改？</a>
		</div>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>