<?php
$data = $this->data;
$orders = $data['orders'];
$pages = $data['pages'];
$page = $this->page;
?>
<div class="header"> 
	<h1 class="page-title">咨询医生订单列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">咨询医生订单列表</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<table class="table table-bordered table-hover">
		<caption></caption>
		  <thead>
		    <tr>
		      <th>订单号</th>
		      <th>所属用户</th>
		      <th>用户角色</th> 
		      <th>咨询的医生</th> 
		      <th>总价</th>
		      <th>支付状态</th>
		      <th>详情</th>
		      <th>删除</th>
		    </tr>
		  </thead>
		  <tbody>
		  <?php if(count($orders)>0){?>
		    
		    <?php foreach ($orders as $record){?>
		    <tr>
		      <td><?php echo $record->getOrder_id();?></td>
		      <td><?php echo Yy_Utils::getAccount($record->getUid(),$record->getUrole());?></td>
		      <td><?php echo Yy_Utils::getUserRole($record->getUrole())?></td>
		      <td><?php echo Yy_Utils::getAccount($record->getTodid(), 2);?></td>
		      <td><?php echo $record->getTotal_price();?></td>	   
		      <td><?php if($record->getPayment_status() == 1){echo "已支付";}else{echo "未支付";}?></td>   
		      <td><a href="/consult/orderview?id=<?php echo $record->getId();?>">详情</a></td>
		      <td><a href="#myModal<?php echo $record->getId();?>" role="button"  data-toggle="modal" >删除</a></td>
		       </tr>

<!-- Modal -->
<div id="myModal<?php echo $record->getId();?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">删除订单号为（<?php echo $record->getOrder_id();?>）的咨询订单</h3>
  </div>
  <div class="modal-body">
    <p>您确定删除订单号为（<?php echo $record->getOrder_id();?>）的咨询订单吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $record->getId();?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $record->getId();?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/consult/orderdel",
				data:"id=<?php echo $record->getId();?>",
				success:
					location.reload(),
			});
		});
});

</script>		       		       
		      <?php }?>		   
		    <?php }else{?>
		   	<tr>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		    </tr>
		    <?php }?>
		  </tbody>
		</table>
		<div class="pagination" style="text-align: center;">
		  <ul>
		  <?php if($page<=1){ ?>
		  <li><a href="/consult/order?page=<?php echo $page;?>" class="disabled btn"> 前一页 </a></li>
		  <?php }else{?>
		  <li><a href="/consult/order?page=<?php echo $page - 1;?>"> 前一页 </a></li>
		  <?php }?>
		    
		  <?php if($page>=$pages){ ?> 
		  <li><a href="/consult/order?page=<?php echo $page;?>" class="disabled btn"> 后一页</a></li>
		  <?php }else{ ?> 
		  <li><a href="/consult/order?page=<?php echo $page + 1;?>"> 后一页</a></li>		  
		  <?php }?>
		  </ul>
		</div>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>