<?php $order = $this->order;?>
<div class="header"> 
	<h1 class="page-title">咨询医生订单详情</h1>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($order){?>
		<table class="table table-bordered table-hover">
<!--  
		<tr>
		<td>编号</td>
		<td><?php echo $order->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width:10%">订单号</td>
		<td><?php echo $order->getOrder_id();?></td>
		</tr>
		<tr>
		<?php 
		if($order->getUrole() == 1){
			$url = "/nuser/view?id=";
		}elseif($order->getUrole() == 2){
			$url = "/doctor/view?id=";
		}elseif($order->getUrole() == 3){
			$url = "/hospital/view?id=";
		}else{
			$url = "#";
		}
		if($url != '#'){
			$url = $url.$order->getUid();
		}
		?>
		<td>所属用户</td>
		<td><a target="_blank" href="<?php echo $url;?>"><?php echo Yy_Utils::getAccount($order->getUid(), $order->getUrole());?></a></td>
		</tr>
		<tr>
		<td>用户角色</td>
		<td><?php echo Yy_Utils::getUserRole($order->getUrole());?></td>
		</tr>
		<tr>
		<td>咨询的医生</td>
		<td><a target="_blank" href="/doctor/view?id=<?php echo $order->getTodid();?>"><?php echo Yy_Utils::getAccount($order->getTodid(), 2);?></a></td>
		</tr>
		<tr>
		<td>总价</td>
		<td><?php echo $order->getTotal_price();?></td>
		</tr>
		<tr>
		<td>支付状态</td>
		<td><?php if($order->getPayment_status() == 1){echo "已支付";}else{echo "未支付";};?></td>
		</tr>
		<tr>
		<td>支付信息</td>
		<td><?php echo $order->getRemark();?></td>
		</tr>
		<tr>
		<td>创建时间</td>
		<td><?php echo $order->getCtime();?></td>
		</tr>
		<tr>
		<td>更新时间</td>
		<td><?php echo $order->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($order->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>