<?php 
$from	= @$_GET['from'];
$did	= @$_GET['did'];
?>
<div class="header"> 
	<h1 class="page-title">新增会诊申请手术项目分类</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/diagnosis/departcatedetail">会诊申请手术分类列表</a> <span class="divider">/</span></li>
	<li class="active">新增会诊申请手术分类</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<br />
		<form class="form-horizontal" action="/diagnosis/departcateasyncajax" method="post" enctype="multipart/form-data">
		<?php if($from){?>
		<input type="hidden" id="inputFrom" class="span8" name="from" value="<?php echo $from;?>">
		<?php }?>
		<?php if($did){?>
		<input type="hidden" id="inputDid" class="span8" name="did" value="<?php echo $did;?>">
		<?php }?>		
		<div class="control-group">
		    <label class="control-label" for="inputName">分类名</label>
		    <div class="controls">
		      <input type="text" id="inputName" placeholder="请输入会诊申请手术项目分类名" class="span8" name="name">
		    </div>
		</div>	  
		
		  <div class="control-group">
		    <label class="control-label" for="inputSort">排序</label>
		    <div class="controls">
		      <input type="text" id="inputSort" placeholder="请输入会诊申请手术项目分类排序顺序，数值越小越靠前" class="span8" name="sort">
		    </div>
		  </div>		  
		    <div class="control-group">
		    <label class="control-label" for="inputStatus">状态</label>
		    <div class="controls">
		     <select id="inputStatus" name="status" class="span8">
			  <option value ="1" selected="selected">正常</option>
			  <option value ="0">禁用</option>
			</select>
		    </div>
		  </div>
		    <div class="control-group">
		    <div class="controls">
		      <button type="submit" class="btn">保存</button>
		      <button type="reset" class="btn">重置</button>
		    </div>
		  </div>
		</form>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>