<?php $depart = $this->depart;?>
<div class="header"> 
	<h1 class="page-title">会诊申请手术项目详情</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/diagnosis/departdetail">会诊申请手术项目列表</a> <span class="divider">/</span></li>
	<li class="active">会诊申请手术项目详情</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($depart){?>
		<table class="table table-bordered table-hover" >
<!--  
		<tr>
		<td style="width:10%">编号</td>
		<td><?php echo $depart->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width:10%">手术名称</td>
		<td><?php echo $depart->getName();?></td>
		</tr>	
		
		<tr>
		<td>分类</td>
		<td><?php echo Yy_Utils::getConsultationDepartmentsCategoryNameByCID($depart->getCategory_id());?></td>
		</tr>
					
		<tr>
		<td>排序</td>
		<td><?php echo $depart->getSort();?></td>
		</tr>
		<tr>
		<td>创建时间</td>
		<td><?php echo $depart->getCtime();?></td>
		</tr>
		<tr>
		<td>更新时间</td>
		<td><?php echo $depart->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($depart->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<div style="width:20%">
		<a href="/diagnosis/departupdate?id=<?php echo $depart->getId();?>" class="btn btn-block">是否修改？</a>
		</div>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>