<?php $intro = $this->intro;?>
<div class="header"> 
	<h1 class="page-title">全球会诊介绍详情</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/diagnosis/introdetail">全球会诊介绍列表</a> <span class="divider">/</span></li>
	<li class="active">全球会诊介绍详情</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($intro){?>
		<table class="table table-bordered table-hover" >
<!--  
		<tr>
		<td style="width:10%">编号</td>
		<td><?php echo $intro->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width:10%">标题</td>
		<td><?php echo $intro->getTitle();?></td>
		</tr>
		<tr>
		<td>内容</td>
		<td><?php echo $intro->getContent();?></td>
		</tr>
		<tr>
		<td>图片</td>
		<td><img src="/diagnosis/introimage?id=<?php echo $intro->getId();?>" height="120" width="120" /></td>
		</tr>
		<tr>
		<td>排序</td>
		<td><?php echo $intro->getSort();?></td>
		</tr>
		<tr>
		<td>创建时间</td>
		<td><?php echo $intro->getCtime();?></td>
		</tr>
		<tr>
		<td>更新时间</td>
		<td><?php echo $intro->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($intro->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<div style="width:20%">
		<a href="/diagnosis/introupdate?id=<?php echo $intro->getId();?>" class="btn btn-block">是否修改？</a>
		</div>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>