<?php $price = $this->price;?>
<div class="header">
	<h1 class="page-title">修改全球会诊价格</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/diagnosis/pricedetail">全球会诊价格列表</a> <span class="divider">/</span></li>
	<li class="active">修改全球会诊价格</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->

<br />
<form class="form-horizontal" action="/diagnosis/priceasyncajax" method="post" enctype="multipart/form-data">

 <input type="hidden" id="inputId" placeholder="<?php echo $price->getId();?>" class="span8" name="id" value="<?php echo $price->getId();?>">

  
  <div class="control-group">
    <label class="control-label" for="inputTitle">标题</label>
    <div class="controls">
      <input type="text" id="inputTitle" placeholder="<?php echo $price->getTitle();?>" class="span8" name="title">
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="textareaContent">内容</label>
    <div class="controls">
      <textarea id="textareaContent" class="textbox span8" placeholder="<?php echo $price->getContent();?>" name="content"></textarea>
    </div>
  	</div>  
  
    <div class="control-group">
    <label class="control-label" for="inputSort">排序</label>
    <div class="controls">
      <input type="text" id="inputSort" placeholder="<?php echo $price->getSort();?>" class="span8" name="sort">
    </div>
  	</div>
  <?php 
  $type = $price->getType();
  ?>
		    <div class="control-group">
		    <label class="control-label" for="inputType">类型</label>
		    <div class="controls">
		     <select id="inputType" name="type" class="span8">
		  <?php    if($type == 1){ ?>
			  <option value ="1" selected="selected">个人服务</option>
			  <option value ="2">企业服务</option>
			  <option value ="3">第二医学意见</option>
		 <?php }elseif($type == 2){?>
		 	  <option value ="1">个人服务</option>
			  <option value ="2" selected="selected">企业服务</option>
			  <option value ="3">第二医学意见</option>
		 <?php }elseif($type == 3){ ?>
		 	  <option value ="1">个人服务</option>
			  <option value ="2">企业服务</option>
			  <option value ="3" selected="selected">第二医学意见</option>
		 <?php }?>
			</select>
		    </div>
		  </div>  	
  <div class="control-group">
    <label class="control-label" for="inputStatus">状态</label>
    <div class="controls">
     <select id="inputStatus" name="status" class="span8">
     <?php $status = $price->getStatus();
     if($status == 1){
     ?>
	  <option value ="1" selected="selected">正常</option>
	  <option value ="0">禁用</option>
	  <?php }else{?>
	  <option value ="1">正常</option>
	  <option value ="0" selected="selected">禁用</option>
	  <?php }?>
	</select>
    </div>
  </div>
  
  
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">保存</button>
      <button type="reset" class="btn">重置</button>
    </div>
  </div>
</form>




		<footer>
			<hr>
			<p class="pull-right">虹桥医游网移动互联网项目</p>
			<p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com"
					target="_blank">虹桥医游网</a>
			</p>
		</footer>

	</div>
</div>