<?php $cate = $this->cate;?>
<div class="header">
	<h1 class="page-title">修改热门项目分类信息</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/costperf/catedetail">热门项目分类列表</a> <span class="divider">/</span></li>
	<li class="active">修改热门项目分类信息</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->

<br />
<form class="form-horizontal" action="/costperf/cateasyncajax" method="post" enctype="multipart/form-data">

 <input type="hidden" id="inputId" placeholder="<?php echo $cate->getId();?>" class="span8" name="id" value="<?php echo $cate->getId();?>">

 <div class="control-group">
    <label class="control-label" for="inputName">分类名</label>
    <div class="controls">
      <input type="text" id="inputName" placeholder="<?php echo $cate->getName();?>" class="span8" name="name">
    </div>
  </div>
  
   <div class="control-group">
    <label class="control-label" for="inputFile">图片</label>
    <div class="controls">
      <input type="file" id="inputFile" class="span8" name="img">
    </div>
  </div>
  	
  	<div class="control-group">
    <label class="control-label" for="inputSort">排序</label>
    <div class="controls">
      <input type="text" id="inputSort" placeholder="<?php echo $cate->getSort();?>" class="span8" name="sort">
    </div>
  	</div>
  <div class="control-group">
    <label class="control-label" for="inputStatus">状态</label>
    <div class="controls">
     <select id="inputStatus" name="status" class="span8">
     <?php $status = $cate->getStatus();
     if($status == 1){
     ?>
	  <option value ="1" selected="selected">正常</option>
	  <option value ="0">禁用</option>
	  <?php }else{?>
	  <option value ="1">正常</option>
	  <option value ="0" selected="selected">禁用</option>
	  <?php }?>
	</select>
    </div>
  </div>
  
  
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">保存</button>
      <button type="reset" class="btn">重置</button>
    </div>
  </div>
</form>




		<footer>
			<hr>
			<p class="pull-right">虹桥医游网移动互联网项目</p>
			<p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com"
					target="_blank">虹桥医游网</a>
			</p>
		</footer>

	</div>
</div>