<?php $data = $this->data;?>
<div class="header"> 
	<h1 class="page-title">查看热门项目分类</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">热门项目分类列表</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
				<table class="table table-bordered table-hover">
		<caption></caption>
		  <thead>
		    <tr>
		      <th>分类</th>
		      <th>排序</th>
		      <th>状态</th>
		      <th>详情</th>
		      <th>修改</th> 
		      <th>删除</th>
		    </tr>
		  </thead>
		  <tbody>
		  <?php if(count($data)>0){?>
		    
		    <?php foreach ($data as $da){?>
		    <tr>
		      <td><?php echo $da->getName();?></td>
		      <td><?php echo $da->getSort();?></td>
		      <td><?php if($da->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		      <td><a target="_blank" href="/costperf/cateview?id=<?php echo $da->getId();?>">详情</a></td>
		      <td><a target="_blank" href="/costperf/cateupdate?id=<?php echo $da->getId();?>">修改</a></td>
			  <td><a href="#myModal<?php echo $da->getId();?>" role="button"  data-toggle="modal" >删除</a></td>
		       </tr>
<!-- Modal -->
<div id="myModal<?php echo $da->getId();?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">删除名称为[<?php echo $da->getName();?>]的热门项目分类</h3>
  </div>
  <div class="modal-body">
    <p>您确定删除名称为[<?php echo $da->getName();?>]的热门项目分类吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $da->getId();?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $da->getId();?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/costperf/catedel",
				data:"cid=<?php echo $da->getId();?>",
				success:
					location.reload(),
					
			});
		});
});

</script>
		      <?php }?>		   
		    <?php }else{?>
		   	<tr>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		    </tr>
		    <?php }?>
		  </tbody>
		</table>
		
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>