<div class="header"> 
	<h1 class="page-title">新增积分卡</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">新增积分卡</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<br />
		<form class="form-horizontal" action="/card/asyncajax" method="post" enctype="multipart/form-data">
		  <div class="control-group">
		    <label class="control-label" for="inputName">名称</label>
		    <div class="controls">
		      <input type="text" id="inputName" placeholder="请输入名称" class="span8" name="name">
		    </div>
		  </div>
		  
		  <div class="control-group">
		    <label class="control-label" for="inputOprice">原价</label>
		    <div class="controls">
		      <input type="text" id="inputOprice" placeholder="请输入原价" class="span8" name="oprice">
		    </div>
		  </div>
		  
		  <div class="control-group">
		    <label class="control-label" for="inputDprice">现价</label>
		    <div class="controls">
		      <input type="text" id="inputDprice" placeholder="请输入现价" class="span8" name="dprice">
		    </div>
		  </div>
		  <div class="control-group">
		    <label class="control-label" for="inputPoints">积分数量</label>
		    <div class="controls">
		      <input type="text" id="inputPoints" placeholder="请输入积分数量" class="span8" name="points">
		    </div>
		  </div>		  		  
		    <div class="control-group">
		    <label class="control-label" for="inputStatus">状态</label>
		    <div class="controls">
		     <select id="inputStatus" name="status" class="span8">
			  <option value ="1" selected="selected">正常</option>
			  <option value ="0">禁用</option>
			</select>
		    </div>
		  </div>
		    <div class="control-group">
		    <div class="controls">
		      <button type="submit" class="btn">保存</button>
		      <button type="reset" class="btn">重置</button>
		    </div>
		  </div>
		</form>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>