<?php $card = $this->card;?>
<div class="header">
	<h1 class="page-title">修改积分卡</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/card/detail">积分卡列表</a> <span class="divider">/</span></li>
	<li class="active">修改积分卡</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->

<br />
<form class="form-horizontal" action="/card/asyncajax" method="post" enctype="multipart/form-data">

 <input type="hidden" id="inputId" placeholder="<?php echo $card->getId();?>" class="span8" name="id" value="<?php echo $card->getId();?>">

  
  <div class="control-group">
    <label class="control-label" for="inputName">名称</label>
    <div class="controls">
      <input type="text" id="inputName" placeholder="<?php echo $card->getName();?>" class="span8" name="name">
    </div>
  </div>
 
    <div class="control-group">
    <label class="control-label" for="inputOprice">原价</label>
    <div class="controls">
      <input type="text" id="inputOprice" placeholder="<?php echo $card->getOprice();?>" class="span8" name="oprice">
    </div>
  	</div>
    <div class="control-group">
    <label class="control-label" for="inputDprice">现价</label>
    <div class="controls">
      <input type="text" id="inputDprice" placeholder="<?php echo $card->getDprice();?>" class="span8" name="dprice">
    </div>
  	</div> 
    <div class="control-group">
    <label class="control-label" for="inputPoints">积分数量</label>
    <div class="controls">
      <input type="text" id="inputPoints" placeholder="<?php echo $card->getPoints();?>" class="span8" name="points">
    </div>
  	</div>   		
  <div class="control-group">
    <label class="control-label" for="inputStatus">状态</label>
    <div class="controls">
     <select id="inputStatus" name="status" class="span8">
     <?php $status = $card->getStatus();
     if($status == 1){
     ?>
	  <option value ="1" selected="selected">正常</option>
	  <option value ="0">禁用</option>
	  <?php }else{?>
	  <option value ="1">正常</option>
	  <option value ="0" selected="selected">禁用</option>
	  <?php }?>
	</select>
    </div>
  </div>
  
  
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">保存</button>
      <button type="reset" class="btn">重置</button>
    </div>
  </div>
</form>




		<footer>
			<hr>
			<p class="pull-right">虹桥医游网移动互联网项目</p>
			<p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com"
					target="_blank">虹桥医游网</a>
			</p>
		</footer>

	</div>
</div>