<?php $card = $this->card;?>
<div class="header"> 
	<h1 class="page-title">积分卡详情</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/card/detail">积分卡列表</a> <span class="divider">/</span></li>
	<li class="active">积分卡详情</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($card){?>
		<table class="table table-bordered table-hover">
<!--  	
		<tr>
		<td>编号</td>
		<td><?php echo $card->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width:10%">名称</td>
		<td><?php echo $card->getName();?></td>
		</tr>
		<tr>
		<td>原价</td>
		<td><?php echo $card->getOprice();?></td>
		</tr>
		<tr>
		<td>现价</td>
		<td><?php echo $card->getDprice();?></td>
		</tr>
		<tr>
		<td>积分数量</td>
		<td><?php echo $card->getPoints();?></td>
		</tr>
		<tr>
		<td>创建时间</td>
		<td><?php echo $card->getCtime();?></td>
		</tr>
		<tr>
		<td>更新时间</td>
		<td><?php echo $card->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($card->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<div style="width:20%">
		<a href="/card/update?id=<?php echo $card->getId();?>" class="btn btn-block">是否修改？</a>
		</div>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>