<?php $travels = $this->travels;?>
<div class="header"> 
	<h1 class="page-title">导入<?php echo Yy_Utils::getTravelType($this->type);?>行程</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">导入<?php echo Yy_Utils::getTravelType($this->type);?>行程</li>
 </ul>
 <div class="alert fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>数据导入注意事项</strong> <br/>
            1)位置列只能是“国内”或“国外”这两个词之一；<br/>
            2)成人原价/成人现价/儿童原价/儿童现价列只能是数字；<br/>
            3)状态列只能是“正常”或“禁用”这两个词之一。<br/>
            
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<br />

		<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
		<input type="hidden" id="inputType" class="span8" name="type" value="<?php echo $this->type;?>">

		  
		   <div class="control-group">
		    <label class="control-label" for="inputFile">文件</label>
		    <div class="controls">
		      <input type="file" id="inputFile" class="span8" name="xls">
		    </div>
		   </div>

		    <div class="control-group">
		    <div class="controls">
		      <button type="submit" class="btn">上传并导入</button>
		      <button type="reset" class="btn">重置</button>
		      <a href="/files/travel.xlsx" class="btn">下载模板文件</a>
		    </div>
		  </div>
		</form>

		  <?php if(count($travels)>0){?>
		  <label style="color:red;">已经正常导入到数据库如下数据：</label>
		<table class="table table-bordered table-hover">
		
		  <thead>
		    <tr>
		      <th>位置</th>
		      <th>成人原价</th> 
		      <th>成人现价</th>
		      <th>儿童原价</th>
		      <th>儿童现价</th>
		      <th>地区</th>   
		      <th>大标题</th>  
		      <th>小标题</th>
		      <th>状态</th>
		    </tr>
		  </thead>
		  <tbody>		    
		    <?php foreach ($travels as $record){?>
		    <tr>
		      <td><?php echo Yy_Utils::getTravelLType($record->getLocation_type());?></td>
		      <td><?php echo $record->getAdult_oprice();?></td>
		      <td><?php echo $record->getAdult_dprice();?></td>
		      <td><?php echo $record->getChild_oprice();?></td>
		      <td><?php echo $record->getChild_dprice();?></td>
		      <td><?php echo $record->getArea();?></td>
		      <td><?php echo mb_substr($record->getTitle(), 0,18,'utf-8');?>......</td>
		      <td><?php echo mb_substr($record->getSubtitle(), 0,18,'utf-8');?>......</td>
		      <td><?php if($record->getStatus() == 1){echo "正常";}else{echo "禁用";}?></td>		            
		      <?php }?>		   
		    <?php }?>		
		
		  </tbody>
		</table>		
		
		
		
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>