<?php $travel = $this->travel;?>
<div class="header"> 
	<h1 class="page-title">行程详情</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/travel/detail?type=<?php echo $travel->getType();?>"><?php echo Yy_Utils::getTravelType($travel->getType());?>行程列表</a> <span class="divider">/</span></li>
	<li class="active">行程详情</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($travel){?>
		<table class="table table-bordered table-hover">
<!--
		<tr>
		<td>编号</td>
		<td><?php echo $travel->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width:10%">类型</td>
		<td><?php echo Yy_Utils::getTravelType($travel->getType());?></td>
		</tr>
		<tr>
		<td>位置</td>
		<td><?php echo Yy_Utils::getTravelLType($travel->getLocation_type());?></td>
		</tr>	
		<tr>
		<td>成人原价</td>
		<td><?php echo $travel->getAdult_oprice();?></td>
		</tr>
		<tr>
		<td>成人现价</td>
		<td><?php echo $travel->getAdult_dprice();?></td>
		</tr>
		<tr>
		<td>儿童原价</td>
		<td><?php echo $travel->getChild_oprice();?></td>
		</tr>
		<tr>
		<td>儿童现价</td>
		<td><?php echo $travel->getChild_dprice();?></td>
		</tr>
		<tr>
		<td>地区</td>
		<td><?php echo $travel->getArea();?></td>
		</tr>
		<tr>
		<td>已卖票数</td>
		<td><?php echo $travel->getSales();?></td>
		</tr>
		<tr>
		<td>大标题</td>
		<td><?php echo $travel->getTitle();?></td>
		</tr>
		<tr>
		<td>小标题</td>
		<td><?php echo $travel->getSubtitle();?></td>
		</tr>
		
		<tr>
		<td>图片</td>
		<td><img src="/travel/image?id=<?php echo $travel->getId();?>" height="120" width="120" /></td>
		</tr>
		
		<tr>
		<td>创建时间</td>
		<td><?php echo $travel->getCtime();?></td>
		</tr>	
		<tr>
		<td>更新时间</td>
		<td><?php echo $travel->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($travel->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<div style="width:20%">
		<a href="/travel/update?id=<?php echo $travel->getId();?>" class="btn btn-block">是否修改？</a>
		<hr />
		<a href="/travel/addiadd?id=<?php echo $travel->getId();?>&hmsg=<?php echo $travel->getTitle();?>" class="btn btn-block">是否增加附加信息？</a>
		<a href="/travel/addidetail?id=<?php echo $travel->getId();?>&hmsg=<?php echo $travel->getTitle();?>" class="btn btn-block">是否查看附加信息？</a>
		</div>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>