<?php
$data = $this->data;
$articles = $data['articles'];
$pages = $data['pages'];
$page = $this->page;
$type = $this->type;
$typestr = Yy_Utils::getArticleByType($type);
?>
<div class="header"> 
	<h1 class="page-title"><?php echo $typestr;?>列表</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active"><?php echo $typestr;?>列表</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<table class="table table-bordered table-hover">
		<caption></caption>
		  <thead>
		    <tr>
		      <th>标题</th>
		      <th>内容</th>
		      <th>排序</th> 
		      <th>状态</th> 
		      <th>详情</th>
		      <th>修改</th>
		      <th>删除</th>
		    </tr>
		  </thead>
		  <tbody>
		  <?php if(count($articles)>0){?>
		    
		    <?php foreach ($articles as $record){?>
		    <tr>
		      <td><?php echo $record->getTitle();?></td>
		      <td><?php echo mb_substr($record->getContent(), 0,30,'utf-8');?></td>
		      <td><?php echo $record->getSort();?></td>
		      <td><?php if($record->getStatus() == 1){echo "正常";}else{echo "禁用";}?></td>     
		      <td><a href="/article/view?id=<?php echo $record->getId();?>">详情</a></td>
		      <td><a href="/article/update?id=<?php echo $record->getId();?>">修改</a></td>
		      <td><a href="#myModal<?php echo $record->getId();?>" role="button"  data-toggle="modal" >删除</a></td>
		       </tr>
<!-- Modal -->
<div id="myModal<?php echo $record->getId();?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">删除标题为（<?php echo $record->getTitle();?>）的文章性内容</h3>
  </div>
  <div class="modal-body">
    <p>您确定删除标题为（<?php echo $record->getTitle();?>）的文章性内容吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $record->getId();?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $record->getId();?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/article/delete",
				data:"id=<?php echo $record->getId();?>",
				success:
					location.reload(),
			});
		});
});

</script>		       
		      <?php }?>		   
		    <?php }else{?>
		   	<tr>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		      <td>...</td>
		    </tr>
		    <?php }?>
		  </tbody>
		</table>
		<div class="pagination" style="text-align: center;">
		  <ul>
		  <?php if($page<=1){ ?>
		  <li><a href="/costperf/detail?page=<?php echo $page;?>" class="disabled btn"> 前一页 </a></li>
		  <?php }else{?>
		  <li><a href="/costperf/detail?page=<?php echo $page - 1;?>"> 前一页 </a></li>
		  <?php }?>
		    
		  <?php if($page>=$pages){ ?> 
		  <li><a href="/costperf/detail?page=<?php echo $page;?>" class="disabled btn"> 后一页</a></li>
		  <?php }else{ ?> 
		  <li><a href="/costperf/detail?page=<?php echo $page + 1;?>"> 后一页</a></li>		  
		  <?php }?>
		  </ul>
		</div>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>