<?php 
$article = $this->article;
$typestr = Yy_Utils::getArticleByType($article->getType());
?>

<div class="header"> 
	<h1 class="page-title">
	<?php 
echo $typestr;
	?>详情
	</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/article/detail?type=<?php echo $article->getType();?>"><?php echo $typestr;?>列表</a> <span class="divider">/</span></li>
	<li class="active"><?php echo $typestr;?>详情</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($article){?>
		<table class="table table-bordered table-hover">
<!--  	<tr>
		<td style="width:10%">编号</td>
		<td><?php echo $article->getId(); ?></td>
		</tr>
-->	
		<tr>
		<td style="width:10%">标题</td>
		<td><?php echo $article->getTitle();?></td>
		</tr>
		<tr>
		<td>内容</td>
		<td><?php echo $article->getContent();?></td>
		</tr>
		<tr>
		<td>图片</td>
		<td><img src="/article/image?id=<?php echo $article->getId();?>" height="120" width="120" /></td>
		</tr>	
		<tr>
		<td>排序</td>
		<td><?php echo $article->getSort();?></td>
		</tr>
		<tr>
		<td>类型</td>
		<td><?php echo $typestr;?></td>
		</tr>		
		<tr>
		<td>创建时间</td>
		<td><?php echo $article->getCtime();?></td>
		</tr>	
		<tr>
		<td>更新时间</td>
		<td><?php echo $article->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($article->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
		<div style="width:20%">
		<a href="/article/update?id=<?php echo $article->getId();?>" class="btn btn-block">是否修改？</a>
		</div>
		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>