<div class="header"> 
	<h1 class="page-title">错误页面</h1>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		    <div class="http-error">
		        <h1>Oops!</h1>
		        <p class="info">出现了一个未知的错误</p>
		        <p><i class="icon-home"></i></p>
		        <p><a href="/index">回到后台首页</a></p>
		    </div>
    
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>