<div class="header"> 
	<h1 class="page-title">
	<?php 
	$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
	if($action == 'detail'){
		$title =  "医院列表";
	}elseif($action == 'audit'){
		$title =  "待审核医院列表";
	}else{
		$title =  "列表";
	}
	echo $title;
	?>
	</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<?php if(@$_GET['date']){?>
	<li><a href="/statistics/hospital">医院统计</a> <span class="divider">/</span></li>
	<?php }?>
	<li class="active"><?php echo $title;?></li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<table class="table table-bordered table-hover">
		<caption></caption>
		  <thead>
		    <tr>
		      <th>名称</th>
		      <th>邮箱</th>
		      <th>特色科室</th>
		      <th>医院类型</th>
		      <th>认证级别</th>
		      <th>地区</th>
		      <th>国家</th>
		      <th>积分</th>
		      <th>详情</th>   
		      <th>修改</th>
		      <th>删除</th>  
		    </tr>
		  </thead>
		  <tbody>
		  <?php if(count($this->res)>0){?>
		  <?php foreach ($this->res as $record){?>
		  <tr>
			  <td><?php echo $record['name'];?></td>
			  <td><?php echo $record['email']?></td>
			  <td><?php echo $record['departments'];?></td>
			  <td><?php echo $record['type'];?></td>
			  <td><?php echo Yy_Utils::getCertifiedStar($record['certified']);?></td>
			  <td><?php echo $record['city'];?></td>
			  <td><?php echo $record['country'];?></td>
			  <td><?php echo $record['point'];?></td>
			  <td><a href="/hospital/view?id=<?php echo $record['id'];?>">详情</a></td>
			  <td><a href="/hospital/update?id=<?php echo $record['id'];?>">修改</a></td>
			  <td><a href="#myModal<?php echo $record['id'];?>" role="button"  data-toggle="modal" >删除</a></td>
		  </tr>
<!-- Modal -->
<div id="myModal<?php echo $record['id'];?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">删除账号为（<?php echo $record['email'];?>）的医院</h3>
  </div>
  <div class="modal-body">
    <p>您确定删除账号为（<?php echo $record['email']; ?>）的医院吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $record['id'];?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $record['id'];?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/hospital/delete",
				data:"id=<?php echo $record['id'];?>",
				success:
					location.reload(),
			});
		});
});

</script>		  
		  <?php }?>
		  <?php }else{?>
		  <tr>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>			  
		  </tr>	
		  <?php }?>	  
		  
		  </tbody>
		  </table>
		  
		  <div class="pagination" style="text-align: center;">
		  <ul>
		  <?php if($this->res->getCurrentPageNumber()<=1){ ?>
		  <li><a href="/hospital/<?php echo $action;?>?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber();?>" class="disabled btn"> 前一页 </a></li>
		  <?php }else{?>
		  <li><a href="/hospital/<?php echo $action;?>?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber() - 1;?>"> 前一页 </a></li>
		  <?php }?>
		    
		  <?php if($this->res->getCurrentPageNumber()>=$this->res->count()){ ?> 
		  <li><a href="/hospital/<?php echo $action;?>?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber();?>" class="disabled btn"> 后一页</a></li>
		  <?php }else{ ?> 
		  <li><a href="/hospital/<?php echo $action;?>?date=<?php echo @$_GET['date'];?>&page=<?php echo $this->res->getCurrentPageNumber() + 1;?>"> 后一页</a></li>		  
		  <?php }?>
		  </ul>
		</div>
		  
		  
		  
		  
		  
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>