<div class="header"> 
	<h1 class="page-title">新增医游目的地</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">新增医游目的地</li>
 </ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<br />
		<form class="form-horizontal" action="/destination/asyncajax" method="post" enctype="multipart/form-data">
		
		<div class="control-group">
		    <label class="control-label" for="inputCity">城市</label>
		    <div class="controls">
		      <input type="text" id="inputCity" placeholder="请输入城市" class="span8" name="city">
		    </div>
		</div>
		  
		<div class="control-group">
		    <label class="control-label" for="inputType">位置</label>
		    <div class="controls">
		     <select id="inputType" name="type" class="span8">
			  <option value ="1" selected="selected">国内</option>
			  <option value ="2">国外</option>
			</select>
		    </div>
		 </div>
		 
		  <div class="control-group">
		    <label class="control-label" for="inputLongitude">经度</label>
		    <div class="controls">
		      <input type="text" id="inputLongitude" placeholder="请输入经度" class="span8" name="longitude">
		    </div>
		  </div>
		  <div class="control-group">
		    <label class="control-label" for="inputLatitude">纬度</label>
		    <div class="controls">
		      <input type="text" id="inputLatitude" placeholder="请输入纬度" class="span8" name="latitude">
		    </div>
		  </div>
		  
		   <div class="control-group">
		    <label class="control-label" for="inputFile">图片</label>
		    <div class="controls">
		      <input type="file" id="inputFile" class="span8" name="img">
		    </div>
		   </div>
		  <div class="control-group">
		    <label class="control-label" for="inputSort">排序</label>
		    <div class="controls">
		      <input type="text" id="inputSort" placeholder="请输入目的地排序顺序，数值越小越靠前" class="span8" name="sort">
		    </div>
		  </div>		  
		    <div class="control-group">
		    <label class="control-label" for="inputStatus">状态</label>
		    <div class="controls">
		     <select id="inputStatus" name="status" class="span8">
			  <option value ="1" selected="selected">正常</option>
			  <option value ="0">禁用</option>
			</select>
		    </div>
		  </div>
		    <div class="control-group">
		    <div class="controls">
		      <button type="submit" class="btn">保存</button>
		      <button type="reset" class="btn">重置</button>
		    </div>
		  </div>
		</form>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>