<?php 
$hmsg = @$_GET['hmsg']?:"";
$did = $this->did;
$hospitals = $this->hospitals;
?>
<div class="header"> 
	<h1 class="page-title">新增医游目的地<?php if($hmsg){echo "<span style='color:red;'>".$hmsg."</span>";}?>推荐医院</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/destination/detail">医游目的地列表</a> <span class="divider">/</span></li>
	<li><a href="/destination/view?id=<?php echo $this->did;?>">医游目的地详情</a> <span class="divider">/</span></li>
	<li class="active">新增医游目的地推荐医院</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<label>根据医院名称查找查找</label>
		<form class="form-search">
			<input type="text" class="input-medium search-query" name="hname">
			<input type="hidden" id="inputId" class="span8" name="id" value="<?php echo $did;?>">
			<input type="hidden" id="inputHmsg" class="span8" name="hmsg" value="<?php echo $hmsg;?>">
			<button type="submit" class="btn">搜索</button>
		</form>		
		
		<table class="table table-bordered table-hover">
		<caption></caption>
		  <thead>
		    <tr>
		      <th>名称</th>
		      <th>邮箱</th>
		      <th>特色科室</th>
		      <th>医院类型</th>
		      <th>认证级别</th>
		      <th>地区</th>
		      <th>国家</th>
		      <th>积分</th>
		      <th>详情</th>
		      <th>推荐</th>     
		    </tr>
		  </thead>
		  <tbody>
		  <?php if(count($hospitals)>0){?>
		  <?php foreach ($hospitals as $record){
		  	$hid = $record['id'];
		  	$exists = Yy_Utils::getMapByDidAndHid($did,$hid);
// 		  	if($exists){
// 		  		continue;
// 		  	}
		  ?> <!-- 查看是否已经推荐 -->
		  
		  
		  <tr>
			  <td><?php echo $record['name'];?></td>
			  <td><?php echo $record['email']?></td>
			  <td><?php echo $record['departments'];?></td>
			  <td><?php echo $record['type'];?></td>
			  <td><?php echo Yy_Utils::getCertifiedStar($record['certified']);?></td>
			  <td><?php echo $record['city'];?></td>
			  <td><?php echo $record['country'];?></td>
			  <td><?php echo $record['point'];?></td>
			  <td><a target="_blank" href="/hospital/view?id=<?php echo $record['id'];?>">详情</a></td>
			  <?php if(!$exists){?>
			  <td><a href="#myModal<?php echo $record['id'];?>" role="button"  data-toggle="modal" >推荐</a></td>
			  <?php }else{?>
			  <td><a href="#" class="disabled btn">已推荐</a></td>
			  <?php }?>
		  </tr>

<?php if(!$exists){?>		  
<!-- Modal -->
<div id="myModal<?php echo $record['id'];?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">新增对<?php echo $record['name'];?>的医院推荐</h3>
  </div>
  <div class="modal-body">
    <p>您确定新增对<?php echo $record['name'];?>的医院推荐吗？</p>
  </div>
  <div class="modal-footer">   
    <button id="id_<?php echo $record['id'];?>" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">确定</button>
    <button  class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#id_<?php echo $record['id'];?>").click(function(){
		$.ajax({
				type:"POST",
				url:"/destination/hospitaladdajax",
				data:"did=<?php echo $did;?>&hid=<?php echo $record['id'];?>",
				success:
					location.reload(),
					
			});
		});
});

</script>		  
<?php }?>		  
		  

		  <?php }?>
		  <?php }else{?>
		  <tr>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
			  <td>...</td>
		  </tr>	
		  <?php }?>	  
		  
		  </tbody>
		  </table>
		  
		  <div class="pagination" style="text-align: center;">
		  <ul>
		  <?php if($hospitals->getCurrentPageNumber()<=1){ ?>
		  <li><a href="/destination/hospitaladd?id=<?php echo $did;?>&hmsg=<?php echo $hmsg;?>&page=<?php echo $hospitals->getCurrentPageNumber();?>" class="disabled btn"> 前一页 </a></li>
		  <?php }else{?>
		  <li><a href="/destination/hospitaladd?id=<?php echo $did;?>&hmsg=<?php echo $hmsg;?>&page=<?php echo $hospitals->getCurrentPageNumber() - 1;?>"> 前一页 </a></li>
		  <?php }?>
		    
		  <?php if($hospitals->getCurrentPageNumber()>=$hospitals->count()){ ?> 
		  <li><a href="/destination/hospitaladd?id=<?php echo $did;?>&hmsg=<?php echo $hmsg;?>&page=<?php echo $hospitals->getCurrentPageNumber();?>" class="disabled btn"> 后一页</a></li>
		  <?php }else{ ?> 
		  <li><a href="/destination/hospitaladd?id=<?php echo $did;?>&hmsg=<?php echo $hmsg;?>&page=<?php echo $hospitals->getCurrentPageNumber() + 1;?>"> 后一页</a></li>		  
		  <?php }?>
		  </ul>
		</div>
<div style="width:20%">	
<a href="/hospital/add" class="btn btn-block" target="_blank">医院不存在？</a>
</div>		
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>