<?php $destinations = $this->destinations;?>
<div class="header"> 
	<h1 class="page-title">导入医游目的地</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li class="active">导入医游目的地</li>
</ul>
 <div class="alert fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>数据导入注意事项</strong> <br/>
            1)位置列只能是“国内”或“国外”这两个词之一；<br/>
            2)经度/纬度/排序列只能是数字；<br/>
            3)状态列只能是“正常”或“禁用”这两个词之一。<br/>
            
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<br />

		<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">

		  
		   <div class="control-group">
		    <label class="control-label" for="inputFile">文件</label>
		    <div class="controls">
		      <input type="file" id="inputFile" class="span8" name="xls">
		    </div>
		   </div>

		    <div class="control-group">
		    <div class="controls">
		      <button type="submit" class="btn">上传并导入</button>
		      <button type="reset" class="btn">重置</button>
		      <a href="/files/destination.xlsx" class="btn">下载模板文件</a>
		    </div>
		  </div>
		</form>

		  <?php if(count($destinations)>0){?>
		  <label style="color:red;">已经正常导入到数据库如下数据：</label>
		<table class="table table-bordered table-hover">
		
		  <thead>
		    <tr>
		      <th>城市</th>
		      <th>位置</th> 
		      <th>经度</th>
		      <th>纬度</th>
		      <th>排序</th>
		      <th>状态</th>   
		    </tr>
		  </thead>
		  <tbody>		    
		    <?php foreach ($destinations as $record){?>
		    <tr>
		      <td><?php echo $record->getCity();?></td>
		      <td><?php if($record->getType() == 1){echo "国内";}elseif($record->getType() == 2){echo "国外";}?></td>
		      <td><?php echo $record->getLongitude();?></td>
		      <td><?php echo $record->getLatitude();?></td>
		      <td><?php echo $record->getSort();?></td>
		      <td><?php if($record->getStatus() == 1){echo "正常";}else{echo "禁用";}?></td>		            
		      <?php }?>		   
		    <?php }?>		
		
		  </tbody>
		</table>		
		
		
		
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>