<?php $dest = $this->dest;?>
<div class="header">
	<h1 class="page-title">修改医游目的地信息</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/destination/detail">医游目的地列表</a> <span class="divider">/</span></li>
	<li class="active">修改医游目的地信息</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->

<br />
<form class="form-horizontal" action="/destination/asyncajax" method="post" enctype="multipart/form-data">

 <input type="hidden" id="inputId" placeholder="<?php echo $dest->getId();?>" class="span8" name="id" value="<?php echo $dest->getId();?>">

 <div class="control-group">
    <label class="control-label" for="inputCity">城市</label>
    <div class="controls">
      <input type="text" id="inputCity" placeholder="<?php echo $dest->getCity();?>" class="span8" name="city">
    </div>
  </div>
 
  <div class="control-group">
    <label class="control-label" for="inputLocation_type">位置</label>
    <div class="controls">
     <select id="inputLocation_type" name="location_type" class="span8">
     <?php $type = $dest->getType();
     if($type == 1){
     ?>
	  <option value ="1" selected="selected">国内</option>
	  <option value ="2">国外</option>
	  <?php }else{?>
	  <option value ="1">国内</option>
	  <option value ="2" selected="selected">国外</option>
	  <?php }?>
	</select>
    </div>
  </div>
  	
  	<div class="control-group">
    <label class="control-label" for="inputLongitude">经度</label>
    <div class="controls">
      <input type="text" id="inputLongitude" placeholder="<?php echo $dest->getLongitude();?>" class="span8" name="longitude">
    </div>
  	</div>
  	
  	<div class="control-group">
    <label class="control-label" for="inputLatitude">纬度</label>
    <div class="controls">
      <input type="text" id="inputLatitude" placeholder="<?php echo $dest->getLatitude();?>" class="span8" name="latitude">
    </div>
  	</div>

  <div class="control-group">
    <label class="control-label" for="inputFile">图片</label>
    <div class="controls">
      <input type="file" id="inputFile" class="span8" name="img">
    </div>
  </div>
  	<div class="control-group">
    <label class="control-label" for="inputSort">排序</label>
    <div class="controls">
      <input type="text" id="inputSort" placeholder="<?php echo $dest->getSort();?>" class="span8" name="sort">
    </div>
  	</div>
  <div class="control-group">
    <label class="control-label" for="inputStatus">状态</label>
    <div class="controls">
     <select id="inputStatus" name="status" class="span8">
     <?php $status = $dest->getStatus();
     if($status == 1){
     ?>
	  <option value ="1" selected="selected">正常</option>
	  <option value ="0">禁用</option>
	  <?php }else{?>
	  <option value ="1">正常</option>
	  <option value ="0" selected="selected">禁用</option>
	  <?php }?>
	</select>
    </div>
  </div>
  
  
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">保存</button>
      <button type="reset" class="btn">重置</button>
    </div>
  </div>
</form>




		<footer>
			<hr>
			<p class="pull-right">虹桥医游网移动互联网项目</p>
			<p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com"
					target="_blank">虹桥医游网</a>
			</p>
		</footer>

	</div>
</div>