<?php $dest = $this->dest;?>
<div class="header"> 
	<h1 class="page-title">医游目的地详情</h1>
</div>
<ul class="breadcrumb">
	<li><a href="/index/index">Home</a> <span class="divider">/</span></li>
	<li><a href="/destination/detail">医游目的地列表</a> <span class="divider">/</span></li>
	<li class="active">医游目的地详情</li>
</ul>
<div class="container-fluid">
	<div class="row-fluid">
		<!-- content -->
		<?php if($dest){?>
		<table class="table table-bordered table-hover">
<!-- 	
		<tr>
		<td>编号</td>
		<td><?php echo $dest->getId(); ?></td>
		</tr>
-->
		<tr>
		<td style="width:10%">城市</td>
		<td><?php echo $dest->getCity();?></td>
		</tr>
		<tr>
		<td>位置</td>
		<td><?php if($dest->getType() == 1){echo "国内";}else{echo "国外";}?></td>
		</tr>	

		<tr>
		<td>经度</td>
		<td><?php echo $dest->getLongitude();?></td>
		</tr>
		<tr>
		<td>纬度</td>
		<td><?php echo $dest->getLatitude();?></td>
		</tr>
		<tr>
		<td>图片</td>
		<td><img src="/destination/image?id=<?php echo $dest->getId();?>" height="120" width="120" /></td>
		</tr>
		<tr>
		<td>排序</td>
		<td><?php echo $dest->getSort();?></td>
		</tr>		
		<tr>
		<td>创建时间</td>
		<td><?php echo $dest->getCtime();?></td>
		</tr>	
		<tr>
		<td>更新时间</td>
		<td><?php echo $dest->getUtime();?></td>
		</tr>
		<tr>
		<td>状态</td>
		<td><?php if($dest->getStatus()==1){echo "正常";}else{echo "禁用";}?></td>
		</tr>
		</table>
<div style="width:20%">
		<a href="/destination/update?id=<?php echo $dest->getId();?>" class="btn btn-block">是否修改？</a>
		<hr />
		<a href="/destination/addiadd?id=<?php echo $dest->getId();?>&hmsg=<?php echo $dest->getCity();?>" class="btn btn-block">是否增加附加信息？</a>
		<a href="/destination/addidetail?id=<?php echo $dest->getId();?>&hmsg=<?php echo $dest->getCity();?>" class="btn btn-block">是否查看附加信息？</a>	
		<hr />
		<a href="/destination/hospitaladd?id=<?php echo $dest->getId();?>&hmsg=<?php echo $dest->getCity();?>" class="btn btn-block">是否增加推荐医院？</a>
		<a href="/destination/hospitaldetail?id=<?php echo $dest->getId();?>&hmsg=<?php echo $dest->getCity();?>" class="btn btn-block">是否查看推荐医院？</a>
		<hr />
		<a href="/destination/traveladd?id=<?php echo $dest->getId();?>&hmsg=<?php echo $dest->getCity();?>" class="btn btn-block">是否增加推荐行程？</a>
		<a href="/destination/traveldetail?id=<?php echo $dest->getId();?>&hmsg=<?php echo $dest->getCity();?>" class="btn btn-block">是否查看推荐行程？</a>
</div>

		<?php }?>
        <footer>
        	<hr>
            <p class="pull-right">虹桥医游网移动互联网项目</p>
            <p>&copy; <?php echo date('Y');?> <a href="http://www.hqimt.com" target="_blank">虹桥医游网</a></p>
        </footer>
                    
     </div>
</div>